//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Crud_Ajax_Model.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string address { get; set; }
        public Nullable<long> phoneNumber { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<bool> isDelete { get; set; }
    }
}
