//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponCodeMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CouponCodeMaster()
        {
            this.orders = new HashSet<orders>();
        }
    
        public int couponId { get; set; }
        public string couponCode { get; set; }
        public int couponType { get; set; }
        public Nullable<int> couponFlatAmount { get; set; }
        public Nullable<int> couponPercentage { get; set; }
        public System.DateTime couponExpiryDate { get; set; }
        public int couponUsageLimit { get; set; }
        public int couponIsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders> orders { get; set; }
    }
}
