//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public int orderId { get; set; }
        public Nullable<int> userId { get; set; }
        public string itemId { get; set; }
        public Nullable<int> couponCode { get; set; }
        public System.DateTime orderDate { get; set; }
        public int orderTotalQty { get; set; }
        public Nullable<decimal> orderAmount { get; set; }
        public Nullable<decimal> afterGst { get; set; }
        public Nullable<decimal> totalPayable { get; set; }
    
        public virtual CouponCodeMaster CouponCodeMaster { get; set; }
        public virtual Users Users { get; set; }
    }
}
